export const headerMapping = {
    "-function": (protocol) => protocol === "GPIO" ? "Режим" : "Функция",
    "-variable": "Переменная",
    type: "Тип данных",
    "-aperture": "Апертура",
    description: "Описание",
    isSpecial: "Специальная",
    isLua: "Lua",
    "-asdu": "ASDU",
    "-isSporadically": "СПД",
    "-address": (protocol) => protocol === "GPIO" ? "Номер порта" : "Адрес объекта приема",
    "-pollMode": "Режим опроса",
    "-pollPeriod": (protocol) => protocol === "protocol" ? "Пауза, мс" : "Период опроса, мин",
    "-exec": "Исполнение",
    specialCycleDelay: "Цикличный вызов, сек",
    "-name": (context) => context === "protocol" ? "Протокол" : "Переменная",
    name: "Название",
    coefficient: "Коэффициент расчета",
    cmd: "Команда пользователя",
    group: "Группа",
    archive: "В архив",
    measurement: "Ед. измерения",
    luaExpression: "Lua выражение",
    "-indexName": "Название",
    deviceAddress: "Адрес устройства",
    baudRate: "БОД",
    stopBit: "Стоп-бит",
    parity: "Паритет",
    order2: "Порядок 2 байт",
    order4: "Порядок 4 байт",
    "-isLog": "Логирование",
    "-isClient": "Клиент",
    "-ipaddress": "Адрес",
    port: "Порт",
    lengthOfASDU: "Длина адреса ASDU",
    lengthOfCause: "Длина причины передачи",
    lengthOfAdr: "Длина адреса объекта",
    k: "k",
    w: "w",
    t0: "t0",
    t1: "t1",
    t2: "t2",
    t3: "t3",
    contactBounce: "Период дребезга, мс",
    address: "Адрес объекта приема",
    function: "Функция",
    variable: "Переменная",
    logging: "Логирование",
    pollPeriod: "Период опроса",
    side: "Тип"
};

export const valueMapping = {
    true: "Да",
    false: "Нет",
    "None": "Нет",
    "null": "Нет",
    "": "Не задано",
    "parity_bit": "Бит четности",
    "odd_bit": "Бит нечетности",
    "ttyS0": "RS232",
    "ttyS1": "RS485",
    "LittleEndian": "0-1 младшим вперед",
    "BigEndian": "1-0 старшим вперед",
    "noPoll": "Без опроса",
    "always": "Всегда",
    "manual": "Ручной",
    "start": "На старте",
};
