import {
    LuFolder,
    LuVariable,
    LuUnplug,
    LuCable,
    LuFileDigit,
    LuFileStack,
    LuPackage,
    LuAnchor,
    LuCirclePlus,
    LuChevronsLeftRightEllipsis,
    LuClipboardPaste,
    LuPencil,
    LuTrash2,
    LuScissors,
    LuClipboardCopy,
    LuListTree,
} from "react-icons/lu";
import { GiGoose } from "react-icons/gi";

export const iconsMap = {
    folder: LuFolder,
    variable: LuVariable,
    unplug: LuUnplug,
    cable: LuCable,
    fileDigit: LuFileDigit,
    fileStack: LuFileStack,
    package: LuPackage,
    anchor: LuAnchor,
    plus: LuCirclePlus,
    lrEllipsis: LuChevronsLeftRightEllipsis,
    goose: GiGoose,
    paste: LuClipboardPaste,
    pencil: LuPencil,
    trash: LuTrash2,
    scissors: LuScissors,
    copy: LuClipboardCopy,
    listTree: LuListTree,
};
