export const newTreeTestConst = [
    {
        id: "ae94fe46-5e46-4f8d-be10-8c07b9234386",
        parent: "ae94fe21-5e46-4f8d-be10-8c07b9234386",
        type: "variable",
        text: "ПОТАСКАЙ МЕНЯ",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: "1",
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "ae94fe21-5e46-4f8d-be10-8c07b9234386",
        parent: 0,
        type: "folder",
        text: "Тестовая папка",
        droppable: true,
    },
    {
        id: "4013adb2-64e7-4495-b2ca-1f234759d897",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "7abf631e-4628-4652-b5ff-aa89ca7ec5d8",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "89792d25-35dc-49c0-80f9-84c6a49c1001",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "813f9330-266e-4c72-8afa-cf7e12482568",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "235ae6a3-6b25-438c-8fe5-e49c81a0491d",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "9e7d4834-27f4-4a31-a66f-9bebba4c9c77",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "a6df57a8-9fa6-45c9-8c7d-7d30c2b30a93",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "920a6eb6-e9bc-4baa-a178-4534c18994cb",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "e5478165-8bde-419c-9162-b52bbf0ba561",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "2458d662-8b95-4dc6-a1a1-2e371274221b",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "7cc2e248-5ba7-4787-97b6-248f1a5e05d5",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "warn",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "f27932ad-ea59-4c48-b7a1-76bc845ed657",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "6e85a031-8894-476f-b693-3615da5b1ff6",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "319018da-b93b-4846-b195-652ad4f04be6",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "251995cb-55bf-4c62-ae5d-21be00ea59bb",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "3e936bce-7b79-4d67-a147-260009c0bb55",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "10005ad2-3085-4f7c-b7a7-5a38e2a6c853",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "df8ab6ef-0d40-4b89-904d-02a617f673bb",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
    {
        id: "95ef2148-8ce8-4df5-b43b-ffa186dbd9f8",
        parent: 0,
        type: "variable",
        text: "Новая переменная",
        setting: {
            isSpecial: false,
            type: "bit",
            isLua: false,
            description: "Введите описание",
            cmd: false,
            archive: true,
            group: "noGroup",
            measurement: null,
            coefficient: 1,
            luaExpression: "",
            specialCycleDelay: null,
        },
    },
];
